export const TASK_PUBLIC_PROJECTION = {
  _id: 0,
  taskId: 1,
  workspaceId: 1,
  sectionId: 1,
  text: 1,
  labels: 1,
  image: 1,
  imageUrl: 1,
  imageUrlExpiry: 1,
  reminderAt: 1,
  completed: 1,
  archived: 1,
  deleted: 1,
  deletedAt: 1,
  createdBy: 1,
  workspaceType: 1,
  version: 1,
  createdAt: 1,
  updatedAt: 1,
};
